# Generated by Django 3.0 on 2020-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20200827_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=75)),
                ('CText', models.TextField()),
            ],
        ),
    ]
