# Generated by Django 3.0 on 2020-09-02 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogs', '0007_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sport',
            name='like',
            field=models.ManyToManyField(related_name='sport_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
