# Generated by Django 3.0 on 2020-09-03 19:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_auto_20200903_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
